language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=4.0.0.pre"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
